export const GLOBAL_BASELINE = 6;

export const GLOBAL_SPACING_UNIT_FACTOR_TINY = 1;
export const GLOBAL_SPACING_UNIT_FACTOR_SMALL = 2;
export const GLOBAL_SPACING_UNIT_FACTOR = 4;
export const GLOBAL_SPACING_UNIT_FACTOR_LARGE = 8;
export const GLOBAL_SPACING_UNIT_FACTOR_HUGE = 16;

export const GLOBAL_SPACING_UNIT = `${GLOBAL_BASELINE * GLOBAL_SPACING_UNIT_FACTOR}px`;
export const GLOBAL_SPACING_UNIT_TINY = `${GLOBAL_BASELINE * GLOBAL_SPACING_UNIT_FACTOR_TINY}px`;
export const GLOBAL_SPACING_UNIT_SMALL = `${GLOBAL_BASELINE * GLOBAL_SPACING_UNIT_FACTOR_SMALL}px`;
export const GLOBAL_SPACING_UNIT_LARGE = `${GLOBAL_BASELINE * GLOBAL_SPACING_UNIT_FACTOR_LARGE}px`;
export const GLOBAL_SPACING_UNIT_HUGE = `${GLOBAL_BASELINE * GLOBAL_SPACING_UNIT_FACTOR_HUGE}px`;
